-- ============================================
-- IMMEDIATE FIX FOR LOGIN ISSUE
-- Run this ENTIRE script in Supabase SQL Editor
-- ============================================

-- Step 1: Check if users table exists
SELECT EXISTS (
   SELECT FROM information_schema.tables 
   WHERE table_name = 'users'
);

-- Step 2: Check current users
SELECT * FROM users;

-- Step 3: Delete ALL existing users (clean slate)
DELETE FROM users;

-- Step 4: Insert default users with EXACT credentials
-- Only admin and finance have default accounts
-- Teachers get credentials from Admin
-- Students get credentials from Teacher
INSERT INTO users (user_id, password, role) VALUES
('admin', 'password', 'Admin'),
('finance', 'password', 'Finance');

-- Step 5: Verify users were created correctly
SELECT user_id, password, role, created_at FROM users;

-- Step 6: Check RLS policies
SELECT * FROM pg_policies WHERE tablename = 'users';

-- Step 7: Ensure public access policy exists
DROP POLICY IF EXISTS "Allow public access" ON users;
CREATE POLICY "Allow public access" ON users 
FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- Step 8: Verify realtime is enabled
SELECT * FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'users';

-- ============================================
-- EXPECTED RESULTS:
-- ============================================
-- After running this, you should see ONLY 2 users:
-- user_id  | password | role
-- admin    | password | Admin
-- finance  | password | Finance
--
-- Teacher credentials: Generated by Admin
-- Student credentials: Generated by Teacher
--
-- Now try logging in with:
-- User ID: admin
-- Password: password
-- Role: Admin
-- ============================================
